name: Manual Deploy to EC2 on Merge to Master

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}

      - name: Allow Security group rule to connect Github Actions to Bastion-host
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          VPC_ID: vpc-085bf3ae8486df96a
        run: |
          aws ec2 authorize-security-group-ingress --group-id sg-0b06b360cd966fb8f --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32 

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_OF_TARGET }}

      - name: Run script on EC2
        run: |
          ssh -o StrictHostKeyChecking=yes -J admin@52.6.182.191 admin@172.30.21.166 "sh masterpull.sh"

      - name: Deny Security group rule to connect Github Actions to Bastion-host
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          VPC_ID: vpc-085bf3ae8486df96a
        run: |
          aws ec2 revoke-security-group-ingress --group-id sg-0b06b360cd966fb8f --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32 
